package com.haoge.luanru.music.util;

public interface MusicBroadcastActions {
	String ACTVITY_PLAY_OR_PAUSE = "ACTIVITY_PLAY_OR_PAUSE";
	String SERVICE_PLAYER_PAUSED = "SERVICE_PLAYER_PAUSED";
	String SERVICE_PLAYER_PLAYING = "SERVICE_PLAYER_PLAYING";
	String SERVICE_UPDATE_PROGRESS = "SERVICE_UPDATE_PROGRESS";
	String SERVICE_GET_MUSIC_LIST_COMPLETE = "SERVICE_GET_MUSIC_LIST_COMPLETE";
	String ACTVITY_UODATE_PROGRESS = "ACTVITY_UODATE_PROGRESS";
	String SEEKBAR = "SEEKBAR";
	String ACTVITY_PRE="ACTVITY_PRE";
	String ACTVITY_ITEM = "ACTVITY_ITEM";
	String SERVICE_DOWN_MUSIC = "SERVICE_DOWN_MUSIC";
	String SERVICE_PLAYER_COMPLETION="SERVICE_PLAYER_COMPLETION";
	String SERVICE_REFRESH="SERVICE_REFRESH";
	String SERVICE_DOWN_PIC = "SERVICE_DOWN_PIC";
	String REFRESH_LOCAL_MUSICS = "REFRESH_LOCAL_MUSICS";
	String ACTVITY_SET_LOCAL_APP="ACTVITY_SET_LOCAL_APP";
	String ACTVITY_SET_ONLINE_APP="ACTVITY_SET_ONLINE_APP";
	String REFRESH_ONLINE_MUSICS = "REFRESH_ONLINE_MUSICS";
	String SERVICE_DELETE_FILE = "SERVICE_DELETE_FILE";
	//String ACTVITY_ITEM ="ACTVITY_NEXT_OR_PRE_OR_ITEM";
	String ACTVITY_NEXT ="ACTVITY_NEXT";
	/**
	 * Intent传递的参数：当前播放到的位置
	 */
	String EXTRA_MUSIC_CURRENT_POSITION = "EXTRA_MUSIC_CURRENT_POSITION";
	/**
	 * Intent传递的参数：当前播放的歌曲的时长
	 */
	String EXTRA_MUSIC_DURATION = "EXTRA_MUSIC_DURATION";
}
